# Задержка перед перезагрузкой в секундах
restart-delay: 60

# Сообщение, отправляемое игрокам за 5 секунд до перезагрузки
restart-message: "&cСервер будет перезагружен через %seconds% секунд!"

# Заголовок (Title), отображаемый при перезагрузке
title-message: "&cПерезагрузка!"

# Подзаголовок (Subtitle), отображаемый при перезагрузке
subtitle-message: "&cОсталось %seconds% секунд"

# Сообщение в BossBar
bossbar-message: "&cПерезагрузка сервера через %seconds% секунд"

# Время перезагрузки для каждого дня недели в формате HH:mm (24-часовой формат)
# Если день недели не указан, используется время по умолчанию (03:00).
restart-times:
  MONDAY: "04:00"        # Перезагрузка в понедельник в 4:00 утра
  TUESDAY: "10:00"       # Перезагрузка во вторник в 10:00 утра
  WEDNESDAY: "18:00"      # Перезагрузка в среду в 18:00 (6:00 вечера)
  THURSDAY: "03:30"
  FRIDAY: "03:00"
  SATURDAY: "03:00"
  SUNDAY: "03:00"